services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=librarydb'
      - 'POSTGRES_PASSWORD=developer'
      - 'POSTGRES_USER=library'
    ports:
      - '5432:5432'
    networks:
      - public_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - public_network

networks:
  public_network:
    driver:
      bridge